@SQLQueryAI_HostAddress = http://localhost:5275

GET {{SQLQueryAI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{SQLQueryAI_HostAddress}}/api/sql/generate
Content-Type: application/json

"List all orders with order details, customer name placed in December 2023, including order IDs and total amounts."

###

POST {{SQLQueryAI_HostAddress}}/api/sql/execute
Content-Type: application/json

"SELECT o.OrderID, c.CustomerName, o.OrderDate, o.TotalAmount, od.ProductName, od.Quantity, od.Price \nFROM [Order] o\nJOIN OrderDetails od ON o.OrderID = od.OrderID\nJOIN Customer c ON o.CustomerID = c.CustomerID\nWHERE o.OrderDate >= '2023-12-01' AND o.OrderDate < '2024-01-01';"

###

POST {{SQLQueryAI_HostAddress}}/api/sql/generate-and-execute
Content-Type: application/json

"List all orders with order details, customer name placed in December 2023, including order IDs and total amounts."
